### ISSUE TITLE
Update dev version to 1.20.6

### ISSUE THREAD

**Issue by PeppoDevStudio** [Mikedeejay2/SimpleStackPlugin#102]
Update dev version to 1.20.6, please.

**Comment by Mikedeejay2** [comment]
An update for 1.20.6 is being worked on, however, it will take some time as Minecraft has changed a significant amount of code related to maximum stack sizes. 

This is due to maximum stack sizes being configurable via the give command and data packs now. Depending on what you were using SimpleStack for, it might be possible to instead use the `max_stack_size` item component on items you wish to have a custom stack size. See [this Minecraft wiki page](https://minecraft.wiki/w/Data_component_format), and particularly [this section](https://minecraft.wiki/w/Data_component_format#max_stack_size) for modifying maximum stack sizes.

**Comment by PeppoDevStudio** [comment]
Okay update me

**Comment by Mikedeejay2** [comment]
Dev builds have been updated to 1.20.6, the latest build can be downloaded on [GitHub Actions](https://github.com/Mikedeejay2/SimpleStackPlugin/actions/runs/9326636857).
Closing this issue. Please let me know if you have any issues with the update.
