### ISSUE TITLE
Bugs, Items not stacking in inventory on pickup and extra item generation.

### ISSUE THREAD

**Issue by SirCraftypants** [Mikedeejay2/SimpleStackPlugin#28]
OK i've decided to create a new report.

When picking up a stack of items, it's only the first 2 that are stacked and the rest are separated.

Items tested with are Water Bucket and Potion on Paper 1.15.2

This causes a few issues:

If your inventory does not have enough slots, the remaining items that you pick up requiring slots are lost to the void.

If you have an item stack set to say 64, when stacking the 64th item on to a stack of 63, it weirdly generates a 65th of the same item.

The word 'Null' keeps flashing on screen every now and then too.

**Comment by Mikedeejay2** [comment]
I'm having trouble finding these errors. Have you updated to the latest version that I released yesterday? If the plugin is throwing errors in console can you post one of them here?

**Comment by SirCraftypants** [comment]
Hi, yes updated and it fixed it as far as allowing me to stack items myself, no errors in Console. If you're not getting the same issue then may be it's a compatibility issue between your plugin and the non premium Rosestacker plugin, shame cos i like them both.

**Comment by Mikedeejay2** [comment]
That could be it. Because of the way that vanilla Minecraft works I've had to re-code most of the parts that tell an item how much it should stack too. I'm guessing that Rosestacker also does something similar to this so when both plugins are trying to stack an item together at the same time it would cause the bugs that were mentioned above. 

I wonder if you are able to disable the item stacking in Rosestacker but keep everything else from that plugin enabled? If you can't, that would be a nice feature for them to add because it would fix this issue.

**Comment by Mikedeejay2** [comment]
Closing this issue because this isn't an issue with Simple Stack but a compatibility issue between the feature sets of Simple Stack and Rosestacker. The best suggestion I can give you is to look through the Rosestacker config to search for an option to disable item stacking so that the plugins don't have compatibility issues.
