### ISSUE TITLE
NullPointerException issue

### ISSUE THREAD

**Issue by MrFreasy** [Mikedeejay2/SimpleStackPlugin#40]
When someone tries to stack potions in the inventory this error is thrown in the console: https://pastebin.com/3PFba3sy

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! I was unable to reproduce this bug on my server but I've implemented a fix based on the error you gave me. 
If you'd like to use this fix before the next version is released, download the zip file I've attached to this comment and use the simplestack jar file found inside. 
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5448633/simplestack-1.3.0-SNAPSHOT.zip)
If this fix still doesn't fix the error or presents a new issue, please report the issue here.
