### ISSUE TITLE
Shulker Problem

### ISSUE THREAD

**Issue by EternalHittMan** [Mikedeejay2/SimpleStackPlugin#41]
When I put the item on the shulker, the stacked item gets corrupted and deleted.

**Comment by Mikedeejay2** [comment]
Thanks for reporting! I've just fixed this bug, if you'd like to use this fix before the next version is released, download the zip file I've attached to this comment and use the simplestack jar file found inside.
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5471884/simplestack-1.3.0-SNAPSHOT.zip)
If this fix still doesn't fix the error or presents a new issue, please report the issue here.
