### ISSUE TITLE
Some items will not stack despite being configured in the plugin.

### ISSUE THREAD

**Issue by Kenaestic** [Mikedeejay2/SimpleStackPlugin#58]
For example, buckets stack but a lava bucket won't even though it's configured in the config. Some other items I found won't stack:

- water_bucket
- milk_bucket
- all music discs
- potions

Here is my config:
https://pastebin.pl/view/b5628d58

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! The issue that was happening here was that you had items in the item amounts list but the items weren't also in the item types list. This was an issue because when whitelist mode was enabled it would ignore any items in the item amounts list if they weren't also in the item types list. I've made a change that allows items in the item amounts list to bypass this because it seems repetitive that all items would have to be in two separate lists.

**Comment by Kenaestic** [comment]
> 
> 
> Thanks for the bug report! The issue that was happening here was that you had items in the item amounts list but the items weren't also in the item types list. This was an issue because when whitelist mode was enabled it would ignore any items in the item amounts list if they weren't also in the item types list. I've made a change that allows items in the item amounts list to bypass this because it seems repetitive that all items would have to be in two separate lists.

I was reading through the config and realized I'm an idiot. I came back here to correct myself but you already answered. I can confirm it works when in blacklist mode, thanks!
